### ISSUE TITLE
[Feat] CreateNameView 작업

### ISSUE THREAD

**Issue by ChrisP-00** [DeveloperAcademy-POSTECH/mc3-team6-nspu#12]
## 🛠 Issue

CreateNameView의 고양이 이름을 조건에 맞게 지을 수 있도록 합니다. 
Lottie를 재생합니다.  

## 📝 To-do

- [x] 고양이 이름 조건 설정 (공백x, 특수문자x, 9글자 이내)
- [x] Lottie 재생 기능 (LottieView) 
- [x] 로티 재생 확인을 위한 임시 에셋 추가 (firstCat)
- [x] 고양이 이름 설정하는 버튼 스타일 추가 (CatButtonStyle)
- [x] 하이파이 적용 (색상, padding 등)
- [x] 고양이 이름 확정 시 뜨는 알림 hifi 적용 -> Default system color (Blue)로 사용 후 추후 수정 시 이슈 생성 예정

**Comment by ChrisP-00** [comment]
- 고양이 이름 확정 시 뜨는 알림 hifi 적용 -> Default system color (Blue)로 사용 후 추후 수정 시 이슈 생성 예정
