### ISSUE TITLE
[Feat] SettingPopupView 설정뷰 작업 

### ISSUE THREAD

**Issue by ChrisP-00** [DeveloperAcademy-POSTECH/mc3-team6-nspu#17]
## 🛠 Issue

설정에 대한 뷰 입니다. 

## 📝 To-do

- 버튼들 
- [x] PUSH 알림 on - off
- [x] 알림 시각 설정
- [x] 배경 음악 on - off 
- [x] 효과음 on - off 
- 기능
- [x] AudioManager (Audio 관리)  
- [x] 설정값 저장 하기 (AppStorage -> UserDefaults)
- [x] Push 알림 기능 (Local Notification)
- [x] 권한 요청 Action Sheet 추가

**Comment by ChrisP-00** [comment]
- Audio manage & Local notification 기능 구현.
- 추가 작업 필요 시 새 이슈 생성 예정

**Comment by ChrisP-00** [comment]
기능 추가 완료 하여 issue 닫습니다. 
추가 작업은 다른 issue로 작업 예정입니다.
