### ISSUE TITLE
[FEAT] StageView Detail Works

### ISSUE THREAD

**Issue by psangwon62** [DeveloperAcademy-POSTECH/mc3-team6-nspu#58]
## 🛠 Issue
StageView 디테일을 잡는 작업입니다.

## 📝 To-do
- [x] Stage Image 크기 조정
- [x] SVG overlay로 건물만 클릭되도록 조정
- [x] 고양이 발 찍기
- [x] 자동 스크롤 구현
- [x] 건물 정보 레이아웃 세부 조정
