### ISSUE TITLE
[Feat]: MainView의 냥이 애니메이션

### ISSUE THREAD

**Issue by zyeongPark** [DeveloperAcademy-POSTECH/mc3-team6-nspu#66]
## 🛠 Issue

메인뷰에서 냥이가 올라갈 때 애니메이션 추가하고 데이터에 따라 위치가 변화할 수 있도록 합니다. 
올라가다가 멈췄을 때 고양이가 앉는 로티로 바뀔 수 있도록 합니다. 

## 📝 To-do

- [ ] 고냥이 애니메이션 자연스럽게 수정합니다. 
- [ ] 계단 올라갔다는 데이터 넘겨받았을 때 고냥이 위치 변화하도록 합니다.
- [ ] 올라가다가 멈췄을 때 walk -> sit으로 로티 이미지 바뀔 수 있도록 합니다.
