### ISSUE TITLE
[Feat] Watch 기능 구현

### ISSUE THREAD

**Issue by jay1261** [DeveloperAcademy-POSTECH/mc3-team6-nspu#93]
## 🛠 Issue
Watch 기능 구현

## 📝 To-do
- [ ] iOS to Watch total층수 데이터 전송
- [ ] Watch CoreMotion으로 실시간으로 데이터 증가하는 뷰
- [ ] 워치 Lottie 뷰
- [ ] 계단 오르는 중임을 자동감지 ?

**Comment by jay1261** [comment]
산타 선생님께..
